-- CREATE TABLE aparelhos(
--     id                  SERIAL PRIMARY KEY,
--     nome                VARCHAR(100) NOT NULL,
--     tipo                VARCHAR(50),
--     status              VARCHAR(20)  DEFAULT 'ok',
--     ultima_manutencao   DATE,
--     precisa_manutencao  BOOLEAN DEFAULT false,
--     observacao          text,
--     uso_hoje            INTEGER DEFAULT 0,
--     created_at          TIMESTAMPTZ DEFAULT NOW()
-- );

-- CREATE TABLE energia(
--     id                  SERIAL PRIMARY KEY,
--     numero_contador     VARCHAR(50) UNIQUE,
--     total_disponivel_kwh DECIMAL(10,2) NOT NULL,
--     consumo_diario_kwh  DECIMAL(10,2) NOT NULL,
--     created_at          TIMESTAMPTZ DEFAULT NOW()
-- );

-- CREATE TABLE recarga_energia(
--     id                  SERIAL PRIMARY KEY,
--     data                DATE CURRENT_DATE,
--     valor_kwh           DECIMAL(10,2) NOT NULL,
--     valor_pago          DECIMAL(10,2) NOT NULL,
--     created_at          TIMESTAMPTZ DEFAULT NOW()
-- );

-- CREATE TABLE jogos_do_dia(
--     id                  SERIAL PRIMARY KEY,
--     jogo                VARCHAR(140) NOT NULL,
--     quantidade          INTEGER NOT NULL,
--     valor_por_jogo      DECIMAL(10,2) NOT NULL,
--     total               DECIMAL(10,2) GENERATED ALWAYS AS (quantidade * valor_por_jogo) STORED,
--     data                DATE DEFAULT CURRENT_DATE,
--     created_at          TIMESTAMPTZ DEFAULT NOW()
-- );

-- CREATE TABLE ganhos_diarios(
--     data                DATE PRIMARY KEY,
--     total               DECIMAL(10,2) NOT NULL
-- );

-- CREATE TABLE notificacoes(
--     id                  SERIAL PRIMARY KEY,
--     mensagem            TEXT NOT NULL,
--     tipo                VARCHAR(20) DEFAULT 'info',
--     lida                BOOLEAN  DEFAULT false,
--     data_criacao        TIMESTAMPTZ DEFAULT NOW()
-- );
-- CREATE TABLE atividade_recente(
--     id                  SERIAL PRIMARY KEY,
--     acao                TEXT NOT NULL,
--     perfil              VARCHAR(50),
--     data_criacao        TIMESTAMPTZ DEFAULT NOW()
-- );

-- CREATE TABLE USUARIOS(
--     id SERIAL PRIMARY KEY,
--     nome VARCHAR(100) NOT NULL,
--     email VARCHAR(150) UNIQUE NOT NULL,
--     senha_hash  VARCHAR(255) NOT NULL,
--     perfil      VARCHAR(10) CHECK(perfil IN('admin','super')) NOT NULL,
--     ativo BOOLEAN DEFAULT true,
--     criado_em   TIMESTAMPTZ DEFAULT NOW()
-- )




-- {
--   "name": "grow-games-lanhouse",
--   "version": "1.0.0",
--   "description": "Sistema de comunicacao interna entre Super Admin e Admins - Grow Games Lan House",
--   "homepage": "https://github.com/SCTech-MZ/growgames#readme",
--   "bugs": {
--     "url": "https://github.com/SCTech-MZ/growgames/issues"
--   },
--   "repository": {
--     "type": "git",
--     "url": "git+https://github.com/SCTech-MZ/growgames.git"
--   },
--   "license": "MIT",
--   "author": "silviocustodiotech",
--   "main": "dist/server.js",
--   "type": "module",
--   "engines": {
--     "node": "20.x"
--   },
--   "scripts": {
--     "dev": "ts-node-dev dist/index.js",
--     "build": "tsc",
--     "db:migrate": "node src/config/database.ts",
--     "seed": "ts-node src/scripts/seed.ts",
--     "start": "node src/index.js",
--     "create:super-admin": "ts-node-dev --transpile-only scripts/createSuperAdmin.ts",
--     "clean": "rimraf node_modules dist"
--   },
--   "dependencies": {
--     "@neondatabase/serverless": "^1.1.0",
--     "bcrypt": "^5.1.1",
--     "cors": "^2.8.5",
--     "dotenv": "^16.6.1",
--     "express": "^4.19.2",
--     "fs": "^0.0.1-security",
--     "jsonwebtoken": "^9.0.2",
--     "pg": "^8.12.0",
--     "rimraf": "^6.1.3"
--   },
--   "devDependencies": {
--     "@types/bcrypt": "^5.0.2",
--     "@types/cors": "^2.8.17",
--     "@types/express": "^4.17.21",
--     "@types/jsonwebtoken": "^9.0.6",
--     "@types/node": "^20.19.43",
--     "@types/pg": "^8.11.6",
--     "ts-node-dev": "^2.0.0",
--     "typescript": "^5.5.3"
--   }
-- }